[tool.briefcase]
project_name = "weatherman"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/weatherman"
license = "MIT license"
author = '@pystar'
author_email = "pystar@gmail.com"

[tool.briefcase.app.weatherman]
formal_name = "weatherman"
description = "A simple weather app."
icon = "src/weatherman/resources/weatherman"
sources = ['src/weatherman']
requires = []


[tool.briefcase.app.weatherman.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.weatherman.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.weatherman.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.weatherman.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.weatherman.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
